- name: "Creates directory"
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "artifact-backend.tar.gz"
    dest: "~/backend/artifact-backend.tar.gz"


- name: "Extract backend"
  unarchive:
    remote_src: yes
    src: "~/backend/artifact-backend.tar.gz"
    dest: "~/backend"

- name: "Run the web server"
  shell:
    cmd: |
      cd ~/backend
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready