- name: "Creates directory"
  become: yes
  file:
    path: ~/server
    state: directory
    mode: 0777

- name: "Copy compressed backend folder"
  become: yes
  copy:
    src: artifact-backend.tar.gz
    dest: ~/server

- name: "Extract backend"
  become: yes
  shell: |
    cd ~/server
    tar -vxf artifact-backend.tar.gz
    rm -f artifact-backend.tar.gz

- name: "Run the web server"
  shell:
    cmd: |
      cd ~/server
      npm install
      pm2 stop default
      pm2 start npm -- start